"""
Inverse-method comparison: CNN vs GA vs hybrid
==============================================

Benchmark the three inverse (pattern -> parameter) approaches on a set of
*known* targets, so we can report parameter error (vs ground truth), pattern
reconstruction error, the number of forward simulations used, and wall-clock:

  1. CNN only          -- one forward pass (Stage 1).
  2. GA (cold start)    -- gradient-free search over (F, k) from scratch.
  3. Hybrid (CNN -> NM) -- CNN warm start + Nelder-Mead refinement (Stage 1+2).

All three optimize/are scored against the SAME objective (pattern MSE on the
64x64 field) and the SAME forward-simulator settings, so the comparison is fair.
Targets are generated by simulating sampled (F, k) with a fixed seed; the
optimizers simulate with the same seed, so a near-perfect match is attainable
and the real differentiators become accuracy and cost.

Usage (from repo root):
    python3 scripts/compare_methods.py                       # defaults
    python3 scripts/compare_methods.py --targets 8 --steps 2500
    python3 scripts/compare_methods.py --model scripts/models/cnn_v2_20000.pt

Outputs:
    scripts/models/method_comparison.csv
    scripts/models/method_comparison.png
"""

import argparse
import sys
import time
from pathlib import Path

import numpy as np
import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt

import torch

sys.path.insert(0, str(Path(__file__).resolve().parent))
import analyzer_core as core  # noqa: E402

MODEL_DIR = core.ROOT / "scripts" / "models"


# -----------------------------
# Model loading (any checkpoint)
# -----------------------------
def load_model(path: Path) -> core.CNNRegressorV2:
    model = core.CNNRegressorV2().to(core.DEVICE)
    model.load_state_dict(torch.load(path, map_location=core.DEVICE))
    model.eval()
    return model


def default_model_path() -> Path:
    """Prefer the largest cnn_v2_{N}.pt, else the canonical v2 checkpoint."""
    tagged = sorted(
        MODEL_DIR.glob("cnn_v2_*.pt"),
        key=lambda p: int(p.stem.split("_")[-1]) if p.stem.split("_")[-1].isdigit() else -1,
    )
    return tagged[-1] if tagged else core.MODEL_FILE


# -----------------------------
# Objective helper
# -----------------------------
def obj_from_params(F, k, target_64, steps, seed):
    sim_64 = core.to_64(core.normalize(core.simulate(F, k, steps=steps, seed=seed)))
    return core.mse(sim_64, target_64), sim_64


# -----------------------------
# Cold-start GA over (F, k)
# -----------------------------
def ga_invert(target_64, ranges, *, steps, seed, pop=10, gens=6,
              elite=2, mut_rate=0.5, rng=None):
    f_min, f_max, k_min, k_max = ranges
    if rng is None:
        rng = np.random.default_rng(0)
    n_evals = 0

    def rand_ind():
        return [rng.uniform(f_min, f_max), rng.uniform(k_min, k_max)]

    def clamp(ind):
        ind[0] = min(max(ind[0], f_min), f_max)
        ind[1] = min(max(ind[1], k_min), k_max)
        return ind

    pop_list = [rand_ind() for _ in range(pop)]
    best = None
    for _ in range(gens):
        scored = []
        for ind in pop_list:
            err, _ = obj_from_params(ind[0], ind[1], target_64, steps, seed)
            scored.append((err, ind))
            n_evals += 1
        scored.sort(key=lambda t: t[0])
        if best is None or scored[0][0] < best[0]:
            best = scored[0]

        survivors = [ind for _, ind in scored[:max(2, pop // 2)]]
        nxt = [list(ind) for _, ind in scored[:elite]]
        while len(nxt) < pop:
            p1 = survivors[rng.integers(len(survivors))]
            p2 = survivors[rng.integers(len(survivors))]
            a = rng.random()
            child = [a * p1[0] + (1 - a) * p2[0], a * p1[1] + (1 - a) * p2[1]]
            if rng.random() < mut_rate:
                child[0] += rng.normal(0, (f_max - f_min) * 0.05)
            if rng.random() < mut_rate:
                child[1] += rng.normal(0, (k_max - k_min) * 0.05)
            nxt.append(clamp(child))
        pop_list = nxt

    err, sim_64 = best[0], None
    F_best, k_best = best[1]
    return F_best, k_best, err, n_evals


# -----------------------------
# Main benchmark
# -----------------------------
def main():
    ap = argparse.ArgumentParser(description="Compare CNN vs GA vs hybrid inverse")
    ap.add_argument("--targets", type=int, default=6, help="number of test targets")
    ap.add_argument("--steps", type=int, default=2500, help="simulation steps")
    ap.add_argument("--seed", type=int, default=42, help="simulator seed (shared)")
    ap.add_argument("--maxiter", type=int, default=40, help="Nelder-Mead iterations")
    ap.add_argument("--ga-pop", type=int, default=10)
    ap.add_argument("--ga-gens", type=int, default=6)
    ap.add_argument("--model", type=str, default=None, help="CNN checkpoint path")
    args = ap.parse_args()

    model_path = Path(args.model) if args.model else default_model_path()
    print(f"[compare] model = {model_path.relative_to(core.ROOT)}")
    model = load_model(model_path)
    ranges = core.load_ranges()
    f_min, f_max, k_min, k_max = ranges

    # Reproducible target (F, k) sampled inside the trained range.
    rng = np.random.default_rng(args.seed)
    targets = [
        (float(rng.uniform(f_min, f_max)), float(rng.uniform(k_min, k_max)))
        for _ in range(args.targets)
    ]

    methods = ["CNN", "GA", "Hybrid"]
    acc = {m: {"F_ae": [], "k_ae": [], "recon_mse": [], "evals": [], "time": []}
           for m in methods}

    for ti, (Ft, kt) in enumerate(targets):
        target_64 = core.to_64(core.normalize(
            core.simulate(Ft, kt, steps=args.steps, seed=args.seed)))
        print(f"\n[target {ti+1}/{len(targets)}] true F={Ft:.4f}, k={kt:.4f}")

        # --- CNN only ---
        t0 = time.time()
        cnn = core.predict(model, target_64, ranges=ranges)
        cnn_err, _ = obj_from_params(cnn.F_pred, cnn.k_pred, target_64, args.steps, args.seed)
        dt = time.time() - t0
        acc["CNN"]["F_ae"].append(abs(cnn.F_pred - Ft))
        acc["CNN"]["k_ae"].append(abs(cnn.k_pred - kt))
        acc["CNN"]["recon_mse"].append(cnn_err)
        acc["CNN"]["evals"].append(1)
        acc["CNN"]["time"].append(dt)
        print(f"  CNN    : F={cnn.F_pred:.4f} k={cnn.k_pred:.4f}  mse={cnn_err:.5f}  "
              f"evals=1  {dt:.2f}s")

        # --- GA cold start ---
        t0 = time.time()
        gF, gk, gerr, gevals = ga_invert(
            target_64, ranges, steps=args.steps, seed=args.seed,
            pop=args.ga_pop, gens=args.ga_gens, rng=np.random.default_rng(args.seed + ti))
        dt = time.time() - t0
        acc["GA"]["F_ae"].append(abs(gF - Ft))
        acc["GA"]["k_ae"].append(abs(gk - kt))
        acc["GA"]["recon_mse"].append(gerr)
        acc["GA"]["evals"].append(gevals)
        acc["GA"]["time"].append(dt)
        print(f"  GA     : F={gF:.4f} k={gk:.4f}  mse={gerr:.5f}  "
              f"evals={gevals}  {dt:.2f}s")

        # --- Hybrid (CNN -> Nelder-Mead) ---
        t0 = time.time()
        ref = core.refine(target_64, cnn.F_pred, cnn.k_pred, ranges=ranges,
                          metric="mse", steps=args.steps, seed=args.seed,
                          maxiter=args.maxiter)
        dt = time.time() - t0
        acc["Hybrid"]["F_ae"].append(abs(ref.F_refined - Ft))
        acc["Hybrid"]["k_ae"].append(abs(ref.k_refined - kt))
        acc["Hybrid"]["recon_mse"].append(ref.error_refined)
        acc["Hybrid"]["evals"].append(ref.n_evals)
        acc["Hybrid"]["time"].append(dt)
        print(f"  Hybrid : F={ref.F_refined:.4f} k={ref.k_refined:.4f}  "
              f"mse={ref.error_refined:.5f}  evals={ref.n_evals}  {dt:.2f}s")

    # --- Aggregate ---
    def avg(m, key):
        return float(np.mean(acc[m][key]))

    print("\n=== Method comparison (averaged over targets) ===")
    header = f"{'Method':>8} | {'F_MAE':>8} | {'k_MAE':>8} | {'recon_MSE':>10} | {'evals':>6} | {'time(s)':>8}"
    print(header)
    print("-" * len(header))
    rows = []
    for m in methods:
        row = {
            "method": m,
            "F_mae": avg(m, "F_ae"),
            "k_mae": avg(m, "k_ae"),
            "recon_mse": avg(m, "recon_mse"),
            "evals": avg(m, "evals"),
            "time_s": avg(m, "time"),
        }
        rows.append(row)
        print(f"{m:>8} | {row['F_mae']:>8.5f} | {row['k_mae']:>8.5f} | "
              f"{row['recon_mse']:>10.5f} | {row['evals']:>6.0f} | {row['time_s']:>8.2f}")

    # --- Save CSV ---
    csv = MODEL_DIR / "method_comparison.csv"
    cols = ["method", "F_mae", "k_mae", "recon_mse", "evals", "time_s"]
    lines = [",".join(cols)]
    for r in rows:
        lines.append(",".join(str(r[c]) for c in cols))
    csv.write_text("\n".join(lines) + "\n")

    # --- Plot ---
    fig, ax = plt.subplots(1, 3, figsize=(15, 4.5))
    x = np.arange(len(methods))
    ax[0].bar(x, [r["recon_mse"] for r in rows], color=["#4C72B0", "#DD8452", "#55A868"])
    ax[0].set_xticks(x); ax[0].set_xticklabels(methods)
    ax[0].set_title("Reconstruction MSE (lower better)"); ax[0].set_yscale("log")
    ax[1].bar(x, [r["F_mae"] for r in rows], label="F", width=0.35)
    ax[1].bar(x + 0.35, [r["k_mae"] for r in rows], width=0.35, label="k")
    ax[1].set_xticks(x + 0.17); ax[1].set_xticklabels(methods)
    ax[1].set_title("Parameter MAE (lower better)"); ax[1].legend()
    ax[2].bar(x, [r["evals"] for r in rows], color=["#4C72B0", "#DD8452", "#55A868"])
    ax[2].set_xticks(x); ax[2].set_xticklabels(methods)
    ax[2].set_title("Forward simulations used (lower better)")
    plt.tight_layout()
    plt.savefig(MODEL_DIR / "method_comparison.png", dpi=180)
    plt.close()

    print(f"\nSaved -> {csv}")
    print(f"Saved -> {MODEL_DIR / 'method_comparison.png'}")


if __name__ == "__main__":
    main()
